/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controller.Organisation;

import controller.Enterprise.AddEnterpriseJPanel;
import controller.Enterprise.ViewEnterpriseJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author karthiksonti
 */
public class ManageOrganisationJPanel extends javax.swing.JPanel {
    JPanel layoutContainer;
    /**
     * Creates new form ManageOrganisationJPanel
     */
    public ManageOrganisationJPanel(JPanel layoutContainer) {
        initComponents();
        this.layoutContainer = layoutContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOrganisation = new javax.swing.JButton();
        viewOrganisation = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        addOrganisation.setText("add");
        addOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganisationActionPerformed(evt);
            }
        });

        viewOrganisation.setText("view");
        viewOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrganisationActionPerformed(evt);
            }
        });

        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(addOrganisation)
                .addGap(67, 67, 67)
                .addComponent(viewOrganisation)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backButton)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrganisation)
                    .addComponent(viewOrganisation))
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganisationActionPerformed
        // TODO add your handling code here:
        AddOrganisationJPanel aojp = new AddOrganisationJPanel(layoutContainer);
        layoutContainer.add("AddOrganisationJPanel", aojp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
        
    }//GEN-LAST:event_addOrganisationActionPerformed

    private void viewOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrganisationActionPerformed
        // TODO add your handling code here:
        ViewOrganisationJPanel vojp = new ViewOrganisationJPanel(layoutContainer);
        layoutContainer.add("ViewOrganisationJPanel", vojp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_viewOrganisationActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        layoutContainer.remove(this);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.previous(layoutContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganisation;
    private javax.swing.JButton backButton;
    private javax.swing.JButton viewOrganisation;
    // End of variables declaration//GEN-END:variables
}
