/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Login;

import controller.Adhar.AAdminNewJPanel;
import controller.Admin.AdminJPanel;
import controller.Bank.BankAdminJPanel;
import controller.Doctor.DoctorTaskJPanel;
import controller.Medical.ManageMedicalJPanel;
import controller.Passport.PasportAdminJPanel;
import controller.Person.ManagePersonJPanel;
import controller.Pharma.ViewPharmaOrdersJPanel;
import controller.Police.PoliceAdminJPanel;
import controller.Police.PoliceJPanel;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Database;

/**
 *
 * @author karthiksonti
 */
public class LoginJPanel extends javax.swing.JPanel {
    JPanel layoutContainer;
    Connection conn;
    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel(JPanel layoutContainer) {
        initComponents();
        this.layoutContainer = layoutContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loginButton.setBackground(new java.awt.Color(255, 204, 102));
        loginButton.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/login.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        boolean saveFlag = true;
        String passwordd = password.getText();
        if( saveFlag == true)
        {
            if(username.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please enter username");
                saveFlag = false;
            }
            else if(passwordd.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please enter password");
                saveFlag = false;
            }   
        }
        if(saveFlag == true)
        {
            Database db = new Database();

            try {
                conn = db.connect();
                String sql = "select * from userdata where username=? and password=?";
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setString(1, username.getText());
                statement.setString(2, password.getText());
                ResultSet a = statement.executeQuery();

                if(a.next()) {
                    JOptionPane.showMessageDialog(this, "Login Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                    if(a.getString("role").equals("Person")){
                        ManagePersonJPanel mpjp = new ManagePersonJPanel(layoutContainer, a.getString("username"));
                        layoutContainer.add("ManagePersonJPanel", mpjp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Passport")){
                        PasportAdminJPanel pajp = new PasportAdminJPanel(layoutContainer);
                        layoutContainer.add("PassportAdminJPanel", pajp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Policeadmin")){
                        PoliceAdminJPanel pajp = new PoliceAdminJPanel(layoutContainer);
                        layoutContainer.add("PoliceAdminJPanel", pajp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Police")){
                        PoliceJPanel pjp = new PoliceJPanel(layoutContainer, username.getText());
                        layoutContainer.add("PoliceJPanel", pjp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Medicaladmin")){
                        ManageMedicalJPanel mijp = new ManageMedicalJPanel(layoutContainer);
                        layoutContainer.add("ManageIdentityJPanel", mijp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Doctor")){
                        DoctorTaskJPanel dtjp = new DoctorTaskJPanel(layoutContainer, a.getString("username"));
                        layoutContainer.add("DoctorTaskJPanel", dtjp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Pharmaadmin")){
                        ViewPharmaOrdersJPanel vpojp = new ViewPharmaOrdersJPanel(layoutContainer);
                        layoutContainer.add("ViewPharmaOrdersJPanel", vpojp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Bankadmin")){
                        BankAdminJPanel bajp = new BankAdminJPanel(layoutContainer);
                        layoutContainer.add("ViewPharmaOrdersJPanel", bajp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else if(a.getString("role").equals("Adharadmin")){
                        AAdminNewJPanel aawjp = new AAdminNewJPanel(layoutContainer);
                        layoutContainer.add("AAdminNewJPanel", aawjp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                    else {
                        AdminJPanel ajp = new AdminJPanel(layoutContainer);
                        layoutContainer.add("AdminJPanel", ajp);
                        CardLayout layout = (CardLayout) layoutContainer.getLayout();
                        layout.next(layoutContainer);
                    }
                } else{
                    JOptionPane.showMessageDialog(this, "Login Failed !!!!!!", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception ex) {
                Logger.getLogger(LoginJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            db.disconnect();
            username.setText("");
            password.setText("");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
