/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controller.Person;

import controller.Adhar.AddAdharJPanel;
import controller.Adhar.ViewAdharJPanel;
import controller.Bank.AddBankJPanel;
import controller.Bank.ViewBankJPanel;
import controller.Doctor.BookDoctorJPanel;
import controller.Passport.ApplyPassportJPanel;
import controller.Passport.ManagePassportApplicationsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author karthiksonti
 */
public class ManagePersonJPanel extends javax.swing.JPanel {
    JPanel layoutContainer;
    String username;
    /**
     * Creates new form ManagePersonJPanel
     */
    public ManagePersonJPanel(JPanel layoutContainer, String username) {
        initComponents();
        this.layoutContainer = layoutContainer;
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applyPassport = new javax.swing.JButton();
        addBank = new javax.swing.JButton();
        bookDoctor = new javax.swing.JButton();
        viewPassport = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        viewBankApplications = new javax.swing.JButton();
        manageUser = new javax.swing.JButton();
        addAdhar = new javax.swing.JButton();
        viewAdhar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        applyPassport.setBackground(new java.awt.Color(255, 204, 51));
        applyPassport.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        applyPassport.setText("Apply for Passport");
        applyPassport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        applyPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyPassportActionPerformed(evt);
            }
        });

        addBank.setBackground(new java.awt.Color(255, 204, 51));
        addBank.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        addBank.setText("Apply for Bank Account");
        addBank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBankActionPerformed(evt);
            }
        });

        bookDoctor.setBackground(new java.awt.Color(255, 204, 51));
        bookDoctor.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        bookDoctor.setText("Book Doctor Appointment");
        bookDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bookDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDoctorActionPerformed(evt);
            }
        });

        viewPassport.setBackground(new java.awt.Color(255, 204, 51));
        viewPassport.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        viewPassport.setText("View Passport Applications");
        viewPassport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPassportActionPerformed(evt);
            }
        });

        backButton1.setBackground(new java.awt.Color(255, 204, 51));
        backButton1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        backButton1.setText("<<BACK");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        viewBankApplications.setBackground(new java.awt.Color(255, 204, 51));
        viewBankApplications.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        viewBankApplications.setText("View Bank Applications");
        viewBankApplications.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewBankApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBankApplicationsActionPerformed(evt);
            }
        });

        manageUser.setBackground(new java.awt.Color(255, 204, 51));
        manageUser.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        manageUser.setText("Manage user details");
        manageUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        manageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserActionPerformed(evt);
            }
        });

        addAdhar.setBackground(new java.awt.Color(255, 204, 51));
        addAdhar.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        addAdhar.setText("Apply for Aadhar");
        addAdhar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addAdhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdharActionPerformed(evt);
            }
        });

        viewAdhar.setBackground(new java.awt.Color(255, 204, 51));
        viewAdhar.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        viewAdhar.setText("View Aadhar Details");
        viewAdhar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewAdhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdharActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("People's Work Area");

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(applyPassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUser, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(addAdhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBankApplications, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBank, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewAdhar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewPassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(backButton1)
                .addGap(58, 58, 58)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton1))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBank)
                    .addComponent(bookDoctor)
                    .addComponent(applyPassport))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBankApplications)
                    .addComponent(viewPassport)
                    .addComponent(manageUser))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAdhar)
                    .addComponent(viewAdhar))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDoctorActionPerformed
        // TODO add your handling code here:
        BookDoctorJPanel bdjp = new BookDoctorJPanel(layoutContainer, username);
        layoutContainer.add("ApplyPassportJPanel", bdjp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_bookDoctorActionPerformed

    private void applyPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyPassportActionPerformed
        // TODO add your handling code here:
        ApplyPassportJPanel apjp = new ApplyPassportJPanel(layoutContainer, username);
        layoutContainer.add("ApplyPassportJPanel", apjp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_applyPassportActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        layoutContainer.remove(this);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.previous(layoutContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void viewPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPassportActionPerformed
        // TODO add your handling code here:
        ManagePassportApplicationsJPanel vpjp = new ManagePassportApplicationsJPanel(layoutContainer, username);
        layoutContainer.add("ViewPassportJPanel", vpjp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_viewPassportActionPerformed

    private void addBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBankActionPerformed
        // TODO add your handling code here:
        AddBankJPanel abjp = new AddBankJPanel(layoutContainer, username);
        layoutContainer.add("AddBankJPanel", abjp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_addBankActionPerformed

    private void viewBankApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBankApplicationsActionPerformed
        // TODO add your handling code here:
        ViewBankJPanel vbjp = new ViewBankJPanel(layoutContainer, username);
        layoutContainer.add("ViewBankJPanel", vbjp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_viewBankApplicationsActionPerformed

    private void manageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserActionPerformed
        // TODO add your handling code here:
        ManageUserJPanel mujp = new ManageUserJPanel(layoutContainer, username);
        layoutContainer.add("ManageUserJPanel", mujp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_manageUserActionPerformed

    private void addAdharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdharActionPerformed
        // TODO add your handling code here:ManageUserJPanel mujp = new ManageUserJPanel(layoutContainer, username);
        AddAdharJPanel aajp = new AddAdharJPanel(layoutContainer, username);
        layoutContainer.add("AddAdharJPanel", aajp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
        
    }//GEN-LAST:event_addAdharActionPerformed

    private void viewAdharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdharActionPerformed
        // TODO add your handling code here:
        ViewAdharJPanel vajp = new ViewAdharJPanel(layoutContainer, username);
        layoutContainer.add("ViewAdharJPanel", vajp);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.next(layoutContainer);
    }//GEN-LAST:event_viewAdharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        layoutContainer.remove(this);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.first(layoutContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdhar;
    private javax.swing.JButton addBank;
    private javax.swing.JButton applyPassport;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton bookDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton manageUser;
    private javax.swing.JButton viewAdhar;
    private javax.swing.JButton viewBankApplications;
    private javax.swing.JButton viewPassport;
    // End of variables declaration//GEN-END:variables
}
