/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controller.Enterprise;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.Database;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
/**
 *
 * @author karthiksonti
 */
public class AddEnterpriseJPanel extends javax.swing.JPanel {
    JPanel layoutContainer;
    public static int count = 0;
    /**
     * Creates new form AddEnterpriseJPanel
     */
    public AddEnterpriseJPanel(JPanel layoutContainer) {
        initComponents();
        this.layoutContainer = layoutContainer;
        
        networkChoice.removeAllItems();
        
        for(String s : getNetworks()){
            networkChoice.addItem(s);
        }
    }
    
    public ArrayList<String> getNetworks() {
        ArrayList<String> networkList = new ArrayList();
        Database db = new Database();
        try {
            Connection conn = db.connect();
            String sql = "select network from networks";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet a = statement.executeQuery();
            while(a.next()){
                networkList.add(a.getString("network"));
            }
        } catch (Exception ex) {
            Logger.getLogger(AddEnterpriseJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return networkList;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseName = new javax.swing.JTextField();
        addEnterprise = new javax.swing.JButton();
        networkName = new javax.swing.JLabel();
        networkChoice = new javax.swing.JComboBox<>();
        backButton4 = new javax.swing.JButton();

        jLabel1.setText("Enterprise Name");

        addEnterprise.setText("Add Network");
        addEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseActionPerformed(evt);
            }
        });

        networkName.setText("Network Name");

        backButton4.setText("<<BACK");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(addEnterprise))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(networkName))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(networkChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton4)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(backButton4)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkName)
                    .addComponent(networkChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(addEnterprise)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseActionPerformed
        // TODO add your handling code here:
        boolean saveFlag = true;
        String enterpriseNamee = enterpriseName.getText();
        if(saveFlag == true)
        {
            if(enterpriseName.getText().isEmpty() || enterpriseName.getText().matches("[A-Z a-z]*\\s*?") == false)
            {
                JOptionPane.showMessageDialog(this, "Enter a valid name");
                saveFlag = false;
            }
        }
        String networkChoicee = null;
        if(networkChoice.getItemCount() == 0){
            JOptionPane.showMessageDialog(this, "Please add network");
            saveFlag = false;
            return;
        }else{
             networkChoicee = networkChoice.getSelectedItem().toString();
        }
        if(saveFlag == true)
        {
            Database db = new Database();
            count++;
            try {
                Connection conn = db.connect();
                String sql = "insert into enterprises (id, enterprise, network) values(?,?,?)";
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setInt(1, count);
                statement.setString(2, enterpriseName.getText());
                statement.setString(3, networkChoice.getSelectedItem().toString());
                int a = statement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Enterprise Created Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(AddEnterpriseJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addEnterpriseActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        layoutContainer.remove(this);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.previous(layoutContainer);
    }//GEN-LAST:event_backButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterprise;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JButton backButton4;
    private javax.swing.JTextField enterpriseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> networkChoice;
    private javax.swing.JLabel networkName;
    // End of variables declaration//GEN-END:variables
}
