/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controller.Pharma;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Database;

/**
 *
 * @author rekha
 */
public class ViewPharmaOrdersJPanel extends javax.swing.JPanel {
    JPanel layoutContainer;
    
    /**
     * Creates new form ViewPharmaOrdersJPanel
     */
    public ViewPharmaOrdersJPanel(JPanel layoutContainer) {
        initComponents();
        this.layoutContainer = layoutContainer;
        hospitalName.removeAllItems();
        for(String s : getHospitals()){
            hospitalName.addItem(s);
        }
    }
    
    public ArrayList<String> getHospitals() {
        ArrayList<String> hospitalList = new ArrayList();
        Database db = new Database();
        try {
            Connection conn = db.connect();
            String sql = "select hospitalname from hospitaldata";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet a = statement.executeQuery();
            while(a.next()){
                hospitalList.add(a.getString("hospitalname"));
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewPharmaOrdersJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return hospitalList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        hospitalName = new javax.swing.JComboBox<>();
        goButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel1.setText("Select Hospital to view orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 173, 230, -1));

        BackButton.setBackground(new java.awt.Color(255, 204, 51));
        BackButton.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        BackButton.setText("<<BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 51, -1, -1));

        hospitalName.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        hospitalName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hospitalName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(hospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 169, -1, -1));

        goButton.setBackground(new java.awt.Color(255, 204, 51));
        goButton.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        goButton.setText("Go");
        goButton.setBorder(new javax.swing.border.MatteBorder(null));
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 244, 47, -1));

        jLabel10.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("View Pharma Order Details");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 86, 272, 46));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 51, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        layoutContainer.remove(this);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.previous(layoutContainer);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        boolean saveFlag = true;
        String hospitalNamee = null;
        if(hospitalName.getItemCount() == 0)
        {
            JOptionPane.showMessageDialog(this, "Please select hospital");
            saveFlag = false;
            return;
        }
        if(saveFlag == true)
        {
            PharmaOrdersJPanel pojp = new PharmaOrdersJPanel(layoutContainer, hospitalName.getSelectedItem().toString());
            layoutContainer.add("PharmaOrdersJPanel", pojp);
            CardLayout layout = (CardLayout) layoutContainer.getLayout();
            layout.next(layoutContainer);
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        layoutContainer.remove(this);
        CardLayout layout = (CardLayout) layoutContainer.getLayout();
        layout.first(layoutContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton goButton;
    private javax.swing.JComboBox<String> hospitalName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
